title: 1st International workshop TRIDENT  - Security and Privacy in Models and Data
description: Collocated workshop  to the 9th International Conference on Model and Data Engineering
(MEDI 2019) https://www.irit.fr/MEDI2019/
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
